version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: WebApp.Dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      api:
        condition: service_healthy
      storage:
        condition: service_started
  api:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
      interval: 2s
      timeout: 1m30s
      retries: 5
      start_period: 5s
  batch:
    build:
      context: .
      dockerfile: BatchProcess.Dockerfile
    ports: 
      - "8081:80"
    env_file:
      - .env
    depends_on:
      api:
        condition: service_healthy
      storage:
        condition: service_started
  storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    hostname: storage
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
